routes/web.php
<?php

Auth::routes();


Route::get('/', function () {
    return redirect()->route('home');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/password/recover/{token?}', 'Auth\ResetPasswordController@showResetPasswordForm')->name('reset.show-reset-form');
Route::post('/password/recover/{token}', 'Auth\ResetPasswordController@resetPassword')->name('reset.reset-password');

/**
 * Admin section
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    /**
     * Cat
     */
    Route::group(['prefix' => 'cats', 'as' => 'cats.'], function () {
        Route::get('/', 'CatsController@index')->name('index');
        Route::get('/create', 'CatsController@create')->name('create');
        Route::get('/filter', 'CatsController@filter')->name('filter');
        Route::post('/', 'CatsController@store')->name('store');
        Route::get('/{cat}/edit', 'CatsController@edit')->name('edit');
        Route::patch('/{cat}', 'CatsController@update')->name('update');
        Route::get('/{cat}', 'CatsController@show')->name('show');
        Route::delete('/destroy', 'CatsController@destroy')->name('destroy');
        Route::delete('/{cat}', 'CatsController@delete')->name('delete');
    });

    /**
     * Breed
     */

    Route::group(['prefix' => 'breeds', 'as' => 'breeds.'], function () {
        Route::get('/', 'BreedController@index')->name('index');
        Route::get('/create', 'BreedController@create')->name('create');
        Route::get('/filter', 'BreedController@filter')->name('filter');
        Route::post('/', 'BreedController@store')->name('store');
        Route::get('/{cat}/edit', 'BreedController@edit')->name('edit');
        Route::patch('/{cat}', 'BreedController@update')->name('update');
        Route::get('/{cat}', 'BreedController@show')->name('show');
        Route::delete('/destroy', 'BreedController@destroy')->name('destroy');
        Route::delete('/{cat}', 'BreedController@delete')->name('delete');
    });
});

app/Models/Cats.php
<?php

namespace App\Models;

use App\Filters\CatFilters;
use App\Presenters\EloquentPresenter\CatPresenter;

//cannot use abstract here, because class Cats already extends
class Cats extends Eloquent
{
    protected $fillable = ['name', 'dob', 'breed_id', 'phone_number'];

    /**
     * Application setting
     * @var string
     */

    protected $presenter = CatPresenter::class;
    protected $filter = CatFilters::class;

    /**
     * Relationship
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function breed()
    {
        return $this->belongsTo(Breed::class, 'breed_id', 'id');
    }

    /**
     * Mutator**
     * @param $value
     */
    public function setDobAttribute($value)
    {
        $formattedDate = $this->storeFormattedDate($value);
        $this->attributes['dob'] = $formattedDate;
    }

}

app/Http/Controllers/CatsController.php
<?php

namespace App\Http\Controllers;

use App\Filters\CatFilters;
use App\Http\Requests\CatCreateRequest;
use App\Models\Animal\Cats;
use App\Repositories\Contracts\BreedRepositoryInterface;
use Illuminate\Http\Request;
use App\Repositories\Contracts\CatRepositoryInterface;

class CatsController extends Controller
{
    protected $catRepositoryInterface;
    protected $breedRepositoryInterface;

    public function __construct(       
        CatRepositoryInterface $catRepositoryInterface,
        BreedRepositoryInterface $breedRepositoryInterface
    ) {
        $this->catRepositoryInterface = $catRepositoryInterface;
        $this->breedRepositoryInterface = $breedRepositoryInterface;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breeds = $this->breedRepositoryInterface->all()->pluck('name', 'id');
        $cats = $this->catRepositoryInterface->allWithPaginate();
        return view('admin.cats.index', [
            'cats' => $cats,
            'breeds' => $breeds,
            'request' => request()->all(),
        ]);
    }

    /**
     * Show the layouts for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breeds = $this->breedRepositoryInterface->all()->pluck('name', 'id');
        return view('admin.cats.create', [
            'cat' => new Cats(),
            'breeds' => $breeds
        ]);
    }

    /**
     * Filter cats based on parameters
     * @param CatFilters $catsFilter
     * @return mixed
     */

    public function filter(Request $request, CatFilters $catFilters)
    {        
        $catsFiltered = $this->catRepositoryInterface->filter($catFilters);
        $breeds = $this->breedRepositoryInterface->all()->pluck('name', 'id');
        return view('admin.cats.index', [
            'cats' => $catsFiltered,
            'breeds' => $breeds,
            'request' => $request->all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CatCreateRequest $request)
    {
        $this->catRepositoryInterface->create($request->all());
        return redirect()->route('admin.cats.index')->with('success', 'created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Cats $cat)
    {
        return view('admin.cats.show', ['cat' => $cat]);
    }

    /**
     * Show the layouts for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Cats $cat)
    {
        $breeds = $this->breedRepositoryInterface->all()->pluck('name', 'id');
        return view('admin.cats.edit', [
            'cat' => $cat,
            'breeds' => $breeds
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cats $cat)
    {
        $this->catRepositoryInterface->update($cat->id, $request->all());
        return redirect()->route('admin.cats.show', ['cat' => $cat])->with('success', 'edited');
    }

    /**
     * @param Cats $cat
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete(Cats $cat)
    {
        $this->catRepositoryInterface->destroy($cat->id);
        return redirect()->route('admin.cats.index')->with('success', 'deleted');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {
        $catIds = explode(",", request()->ids);
        $this->catRepositoryInterface->destroy($catIds);
        return redirect()->route('admin.cats.index')->with('success', 'deleted');
    }

}

resources/views/admin/cats/_filter.blade.php
<!-- Filter cat -->
@php
    $breed = !array_key_exists('breed', $request) ? -1 : $request['breed'];
    $gender = !array_key_exists('gender', $request) ? -1 : $request['gender'];
    $keyword = !array_key_exists('keyword', $request) ? "" : $request['keyword'];
@endphp

<form class="form-inline" action="{{ route('admin.cats.filter') }}" method="get" id="filterCat">
    <div class="pull-left">
        <input type="hidden" value="{{csrf_token()}}"/>
        Filter by:
        <select class="form-control" name="breed" onchange="document.getElementById('filterCat').submit();">
            <option value="" selected>--All breed--</option>
            @foreach ($breeds as $key => $value)
                <option value="{{$key}}" @if($key == $breed) {{ 'selected' }} @endif>{{$value}}</option>
            @endforeach
        </select>

        <select class="form-control" name="gender" onchange="document.getElementById('filterCat').submit();">
            @if(strcmp($gender, '') == 0)
                <option value="" @if(strcmp($gender, '') == 0) {{ 'selected' }} @endif>-- All gender--</option>
                <option value="1"> Male</option>
                <option value="0"> Female</option>
            @else
                <option value="">-- All gender--</option>
                <option value="1" @if($gender == 1) {{ 'selected' }} @endif> Male</option>
                <option value="0" @if($gender == 0) {{ 'selected' }} @endif> Female</option>
            @endif

        </select>
    </div>

    <div class="pull-right">
        <div class="btn-group">
            <input id="searchinput" type="search" name='keyword' class="form-control"
                   placeholder="Enter search keyword ..." value="{{ $keyword }}">
            <span id="searchclear" class="glyphicon glyphicon-remove-circle"></span>
        </div>
    </div>

    <div class="clearfix"></div>
    <input name="sort" type="hidden" value="{{ request()->has('sort') ? request()->get('sort'): "" }}" />
</form>

resources/views/admin/cats/_form.blade.php
<div class="form-group">
    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', $cat->name, ['class' => 'form-control']) !!}

</div>
<div class="form-group">
    {!! Form::label('date_of_birth', 'Date of Birth') !!}
    {!! Form::text('dob', $cat->present()->dob, ['class' => 'form-control datepicker']) !!}

</div>
<div class="form-group">
    {!! Form::label('breed_id', 'Breed') !!}
    {!! Form::select('breed_id', $breeds, $cat->breed_id, ['class' => 'form-control']) !!}

</div>

<div class="form-group">
    {!! Form::label('phone_number', 'Phone number (0XXXYYYZZZZ)') !!}
    {!! Form::text('phone_number', $cat->phone_number, ['class' => 'form-control']) !!}

</div>

<div class="form-group">
    {!! Form::label('Gender') !!}

    @if ($cat->gender == 1 || strlen($cat->gender) == 0)
        {!! Form::radio('gender', '1', true) !!} Male
        {!! Form::radio('gender', '0' ) !!} Female
    @else
        {!! Form::radio('gender', '1') !!} Male
        {!! Form::radio('gender', '0', true) !!} Female
    @endif

</div>

{!! Form::submit('Save Cat', ['class' => 'btn btn-primary']) !!}
{!! Form::button('Back', ['class' => 'btn btn-default', 'onclick' => 'history.go(-1)']) !!}

resources/views/admin/cats/create.blade.php
@extends('partial.layouts.content_template')

@section('heading')
    Create new cat
@endsection

@section('panel_heading')
    Enter cat information
@endsection

@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            @include('partial.notifications.errors')

            {!! Form::open(['url' => route('admin.cats.store'), 'method' => 'POST', 'role' => 'form']) !!}
            @include('admin.cats._form')
            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/admin/cats/edit.blade.php
@extends('partial.layouts.content_template')

@section('title')
    Edit cat
@endsection

@section('css')
    <link rel="stylesheet"
          href="{{ asset('assets/components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}"/>
@endsection

@section('heading')
    Edit cat #{{ $cat->id }}
@endsection

@section('panel_heading')
    Enter cat information
@endsection

@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            @include('partial.notifications.errors')

            {!! Form::open(['url' => route('admin.cats.update', ['cat' => $cat]), 'method' => 'PATCH']) !!}
            @include('admin.cats._form')
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/cats/index.blade.php
@extends('partial.layouts.content_template')

@section('title')
    List cat
@endsection

@section('heading')
    Manage cats
@endsection

@section('operations')
    <p class="operations">
        <a href="{{route('admin.cats.create')}}" class="btn btn-primary">
            Create
        </a>

        <a class="operations__delete--hide hide btn btn-danger" onclick="document.getElementById('delete-selected-form').submit()">Delete selected
        </a>
    </p>

<form action="{{ route('admin.cats.destroy') }}" id="delete-selected-form" method="POST">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <input type="hidden" name="ids" />
            </form>
@endsection

@section('panel_heading')
    List cat
@endsection

@section('main_content')

    @include('partial.flash.success')

    @include('admin.cats._filter')

    <br/>

    @if(count($cats) > 0)
        <table class="table table-striped table-bordered">
            <thead class="thead-default">
            <tr>
                <th><input type="checkbox" name="check-all"/></th>
                <th>#</th>
                <th>{{ sort_by('name', 'Cats', 'admin.cats.filter') }}</th>
                <th>Phone</th>
                <th>Breed</th>
                <th>Updated at</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>

            @foreach($cats as $key => $cat)
                <tr>
                    <td><input type="checkbox" name="check-selected" value="{{ $cat->id }}"/></td>
                    <td>{{ $cat->present()->startItem(request()->get('page')) + $key }}</td>
                    <td>
                        <a href={{ route('admin.cats.show', ['cat' => $cat]) }}>
                            {{ $cat->present()->name }}
                        </a>
                    </td>
                    <td>{{ $cat->present()->phone_number }}</td>
                    <td>{{ $cat->breed->name }}</td>
                    <td>{{ $cat->present()->updated_at }}</td>
                    <td>
                        <a href="{{route('admin.cats.edit', ['cat' => $cat])}}">
                            <button class="btn btn-info">Edit</button>
                        </a>
                        <button class="btn btn-danger"
                                onclick="document.getElementById('delete-cat-{{$cat->id}}').submit()">
                            Delete
                        </button>

                        <form id="delete-cat-{{$cat->id}}" style="display: none" method="POST"
                              action="{{route('admin.cats.delete', ['cat' => $cat])}}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                        </form>

                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    @else
        @include('partial.table.empty')
    @endif

    <!-- Pagination -->
    {{ $cats->appends(request()->all())->links() }}

@stop

resources/views/admin/cats/show.blade.php
@extends('partial.layouts.content_template')

@section('title')
    Show cat
@endsection

@section('heading')
    {{ $cat->name }}
@endsection


@section('panel_heading')
    Cat information
@endsection

@section('main_content')
    <div class="container">

        @include('partial.flash.success')

        <form id="deleteCat" action="{{ route('admin.cats.delete', ['cat' => $cat])  }}" name="deleteForm" method="POST"
              style="display: none;">
            {{csrf_field()}}
            {{method_field("DELETE")}}
        </form>

        <p>Last edited: {{ $cat->updated_at->diffForHumans() }}</p>

        <p>Date of Birth: {{ $cat->dob }}</p>
        <p>
            @if ($cat->breed)
                Breed:
                {{ link_to('cats/breeds/'.$cat->breed->name,
                $cat->breed->name) }}
            @endif
        </p>

        <a href="{{ route('admin.cats.edit', ['cat' => $cat]) }}">
            <span class="glyphicon glyphicon-edit"></span>
            Edit
        </a>

        <a href="#" onclick="confirmDeleteCat()">
            <span class="glyphicon glyphicon-trash"></span>
            Delete
        </a>

    </div>
@stop

@section('scripts')
    <script>
        function confirmDeleteCat() {
            event.preventDefault();
            var confirmed = confirm("Are you sure");
            if (confirmed) {
                document.getElementById('deleteCat').submit();
            }
        }
    </script>
@endsection