routes/web.php
<?php

Auth::routes();


Route::get('/', function () {
    return redirect()->route('home');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/password/recover/{token?}', 'Auth\ResetPasswordController@showResetPasswordForm')->name('reset.show-reset-form');
Route::post('/password/recover/{token}', 'Auth\ResetPasswordController@resetPassword')->name('reset.reset-password');

/**
 * Admin section
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    /**
     * Cat
     */
    Route::group(['prefix' => 'cats', 'as' => 'cats.'], function () {
        Route::get('/', 'CatsController@index')->name('index');
        Route::get('/create', 'CatsController@create')->name('create');
        Route::get('/filter', 'CatsController@filter')->name('filter');
        Route::post('/', 'CatsController@store')->name('store');
        Route::get('/{cat}/edit', 'CatsController@edit')->name('edit');
        Route::patch('/{cat}', 'CatsController@update')->name('update');
        Route::get('/{cat}', 'CatsController@show')->name('show');
        Route::delete('/destroy', 'CatsController@destroy')->name('destroy');
        Route::delete('/{cat}', 'CatsController@delete')->name('delete');
    });

    /**
     * Breed
     */

    Route::group(['prefix' => 'breeds', 'as' => 'breeds.'], function () {
        Route::get('/', 'BreedController@index')->name('index');
        Route::get('/create', 'BreedController@create')->name('create');
        Route::get('/filter', 'BreedController@filter')->name('filter');
        Route::post('/', 'BreedController@store')->name('store');
        Route::get('/{cat}/edit', 'BreedController@edit')->name('edit');
        Route::patch('/{cat}', 'BreedController@update')->name('update');
        Route::get('/{cat}', 'BreedController@show')->name('show');
        Route::delete('/destroy', 'BreedController@destroy')->name('destroy');
        Route::delete('/{cat}', 'BreedController@delete')->name('delete');
    });
});

app/Models/Breed.php
<?php

namespace App\Models;

use App\Presenters\EloquentPresenter\BreedPresenter;

class Breed extends Eloquent
{
    protected $fillable = ['name'];
    protected $presenter = BreedPresenter::class;

    public function cats(){
        return $this->hasMany(Cats::class, 'breed_id','id');
    }

    #region App\Eloquent Members


    #endregion
}

app/Http/Controllers/BreedController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\Contracts\BreedRepositoryInterface;
use Illuminate\Http\Request;

class BreedController extends Controller
{
    private $breedRepositoryInterface;
    public function __construct(BreedRepositoryInterface $breedRepositoryInterface)
    {
        $this->middleware(['admin']);
        $this->breedRepositoryInterface = $breedRepositoryInterface;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breeds = $this->breedRepositoryInterface->allWithPaginate();
        return view('admin.breeds.index',[
            'breeds' => $breeds
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/breeds/index.blade.php
@extends('partial.layouts.content_template')

@section('title')
    List breed
@endsection

@section('heading')
    Manage breeds
@endsection

@section('operations')
    <p class="operations">
        <a href="{{route('admin.breeds.create')}}" class="btn btn-primary">
            Create
        </a>

        <a class="operations__delete--hide hide btn btn-danger"
           onclick="document.getElementById('delete-selected-form').submit()">Delete selected
        </a>
    </p>

    <form action="{{ route('admin.breeds.destroy') }}" id="delete-selected-form" method="POST">
        {{ method_field('DELETE') }}
        {{ csrf_field() }}
        <input type="hidden" name="ids"/>
    </form>
@endsection

@section('panel_heading')
    List breed
@endsection

@section('main_content')

    @include('partial.flash.success')

    <br/>

    @if(count($breeds) > 0)
        <table class="table table-striped table-bordered">
            <thead class="thead-default">
            <tr>
                <th><input type="checkbox"/></th>
                <th>#</th>
                <th>Name</th>
                <th>Updated at</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>

            @foreach($breeds as $key => $breed)
                <tr>
                    <td><input type="checkbox" name="check-selected" value="{{ $breed->id }}"/></td>
                    <td>{{ $breed->present()->startItem(request()->get('page')) + $key }}</td>
                    <td>{{ $breed->name }}</td>
                    <td>{{ $breed->present()->updated_at }}</td>
                    <td>
                        <a href="{{route('admin.cats.edit', ['cat' => $breed])}}">
                            <button class="btn btn-info">Edit</button>
                        </a>
                        <button class="btn btn-danger"
                                onclick="document.getElementById('delete-cat-{{$breed->id}}').submit()">
                            Delete
                        </button>

                        <form id="delete-cat-{{$breed->id}}" style="display: none" method="POST"
                              action="{{route('admin.cats.delete', ['cat' => $breed])}}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                        </form>

                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    @else
        @include('partial.table.empty')
    @endif
    <!-- /.table-responsive -->
    {{ $breeds->appends(request()->all())->links() }}
    <!-- Pagination -->
@stop